name: Generate Index JSON

on:
  push:
    paths-ignore:
      - 'docs/**'
      - 'gallerycom/**'  # Ignore changes in specified paths to prevent triggering the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Checkout the repository

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'  # Specify the Python version

    - name: Run indexing script
      run: |
        python ./lib/indexing.py  # Run the script directly without changing directory

    - name: Commit and push if changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add ./lib/index.json  # Make sure to point to the correct path where index.json is generated
        git commit -m "Update index.json" -a || echo "No changes to commit"
        git push
