name: Generate Index JSON

on:
  push:
    paths-ignore:
      - 'docs/**'
      - 'gallerycom/**'
      - 'lib/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Updated to support Node.js 20

    - name: Set up Python
      uses: actions/setup-python@3.10  # Ensure this is the latest version supporting Node.js 20
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pathlib

    - name: Generate Index JSON
      run: |
        cd lib
        python indexing.py

    - name: Commit and push if changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add lib/index.json
        git commit -m "Update index.json in lib directory" -a || echo "No changes to commit"
        git push
