name: Generate Index JSON

on:
  push:
    paths-ignore:
      - 'docs/**'
      - 'gallerycom/**'
      # Removed 'lib/**' from paths-ignore to ensure changes in lib are considered

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'  # Specify the Python version

    - name: Generate Index JSON
      run: |
        cd lib
        python indexing.py  # Executes indexing.py which writes to index.json directly in the lib directory

    - name: Commit and push if changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add index.json  # Adds index.json from the current directory which is 'lib'
        git commit -m "Update index.json" -a || echo "No changes to commit"
        git push
