name: Image Metadata Extraction

on:
  push:
    paths:
      - 'gallerycom/**'

jobs:
  extract-metadata:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Python Dependencies
      run: |
        pip install Pillow

    - name: Install exiftool
      run: |
        sudo apt-get update
        sudo apt-get install -y exiftool

    - name: Extract Filename
      id: extract-filename
      run: echo "::set-output name=filename::${{ github.event.inputs.filename }}"  # Adjust this line to get the correct filename input

    - name: Run Metadata Extraction Script
      run: python lib/library_and_pages_x.py

    - name: Stash any changes
      run: git stash  # Stashes any unstaged changes

    - name: Pull latest changes from the repository
      run: git pull --rebase  # Ensures that the working directory is clean

    - name: Pop the stash
      run: git stash pop  # Restores the changes

    - name: Commit and Push Changes
      run: |
        git config --global user.name 'Mischlichter'
        git config --global user.email 'alex.stephan.weimar@web.de'
        git add lib/metadata.json
        git add docs/sharing/*.html
        git add docs/sharing/*_favicon.ico
        git commit -m "Update image metadata, HTML pages, and favicons" || echo "No changes to commit"
        git push || echo "Failed to push changes. Check for potential conflicts or issues."

    - name: Construct Address and Check Live Status
      run: |
        filename="${{ steps.extract-filename.outputs.filename }}"
        filename="${filename%.*}.html"  # Removes the extension from the filename and adds .html
        url="https://hogeai.com/sharing/$filename"
        while ! curl --output /dev/null --silent --head --fail "$url"; do
          echo "Waiting for $url to be live..."
          sleep 5
        done
        echo "$url is live."
