name: Image Metadata Extraction and Webpage Verification

on:
  push:
    paths:
      - 'gallerycom/**'

jobs:
  extract-metadata:
    runs-on: ubuntu-latest
    outputs:
      html-files: ${{ steps.extract_filenames.outputs.filenames }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Python Dependencies
      run: pip install Pillow

    - name: Install exiftool
      run: |
        sudo apt-get update
        sudo apt-get install -y exiftool

    - name: Run Metadata Extraction Script and Capture Output
      id: extract_filenames
      run: |
        python lib/library_and_pages_x.py
        # Assuming your script echoes paths like "Page created: docs/sharing/filename.html"
        FILE_PATHS=$(grep -oP 'Page created: \Kdocs/sharing/.*?\.html' script_output.txt)
        echo "::set-output name=filenames::$FILE_PATHS"

    - name: Commit and Push Changes
      run: |
        git config --global user.name 'Mischlichter'
        git config --global user.email 'alex.stephan.weimar@web.de'
        git add lib/metadata.json
        git add docs/sharing/*.html
        git add docs/sharing/*_favicon.ico
        git commit -m "Update image metadata, HTML pages, and favicons"
        git push

  check-website:
    needs: extract-metadata
    runs-on: ubuntu-latest

    steps:
    - name: Check if Pages are Live
      run: |
        for filename in ${{ needs.extract-metadata.outputs.html-files }}
        do
          url="https://www.hogeai.com/sharing/${filename}"
          echo "Checking URL: $url"
          if curl --output /dev/null --silent --head --fail "$url"; then
            echo "$url is live!"
          else
            echo "$url is not live."
            exit 1
          fi
        done
