name: Image Metadata Extraction

on:
  push:
    paths:
      - 'gallerycom/**/*.jpg'

jobs:
  extract-metadata:
    runs-on: ubuntu-latest
    outputs:
      html-files: ${{ steps.extract_filenames.outputs.filenames }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Python Dependencies
      run: pip install Pillow

    - name: Install exiftool
      run: sudo apt-get update && sudo apt-get install -y exiftool

    - name: Run Metadata Extraction Script
      run: python lib/library_and_pages_x.py

    - name: Extract Filenames of Pushed JPGs
      id: extract_filenames
      run: |
        FILES=$(git diff --name-only ${{ github.sha }}^ ${{ github.sha }} | grep '\.jpg$')
        HTML_FILES=$(echo "$FILES" | sed 's/.jpg$/.html/' | xargs -I{} echo "docs/sharing/{}")
        echo "::set-output name=filenames::$HTML_FILES"

    - name: Stash any changes
      run: git stash

    - name: Pull latest changes from the repository
      run: git pull --rebase

    - name: Pop the stash
      run: git stash pop

    - name: Commit and Push Changes
      run: |
        git config --global user.name 'Mischlichter'
        git config --global user.email 'alex.stephan.weimar@web.de'
        git add lib/metadata.json
        git add docs/sharing/*.html
        git add docs/sharing/*_favicon.ico
        git commit -m "Update image metadata, HTML pages, and favicons"
        git push

  check-website:
    needs: extract-metadata
    runs-on: ubuntu-latest

    steps:
    - name: Check if Pages are Live
      run: |
        for html_file in ${{ needs.extract-metadata.outputs.html-files }}
        do
          url="https://www.hogeai.com/sharing/${html_file}"
          echo "Checking URL: $url"
          if curl --output /dev/null --silent --head --fail "$url"; then
            echo "$url is live!"
          else
            echo "$url is not live."
            exit 1
          fi
        done
