name: Image Metadata Extraction

on:
  push:
    paths:
      - 'gallerycom/**'

jobs:
  extract-metadata:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Python Dependencies
      run: |
        pip install Pillow  # Add any other necessary Python dependencies

    - name: Install exiftool
      run: |
        sudo apt-get update
        sudo apt-get install -y exiftool

    - name: Run Metadata Extraction Script
      run: python lib/library.py  # Make sure this path is correct

    - name: Commit and Push Changes
      run: |
        git config --global user.name 'Mischlichter'
        git config --global user.email 'alex.stephan.weimar@web.de'
        git add lib/json/metadata.json  # Replace with the actual path
        git commit -m "Update image metadata" || echo "No changes to commit"
        git push
